{
    'name': 'Hospital Management',
    'version': '1.0.0',
    'category': 'Hospital',
    'author': 'CH.AI',
    'sequence': -100,
    'summary': 'Hospital management system',
    'description': """Hospital management system""",
    'depends': [],
    'data': [],
    'demo':[],
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}